# Generated by Django 5.2.17 on 2026-09-30 19:06
#? Elle yazılmaz. Model değişince makemigrations, sonra migrate.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80, verbose_name='İsim')),
                ('eposta', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('icerik', models.TextField(verbose_name='Mesaj')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
