# Generated by Django 5.2.17 on 2026-09-30 19:06
#? Bu dosyayı elle yazma. Model değişince: python manage.py makemigrations
#? Tabloyu oluşturmak için: python manage.py migrate

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, verbose_name='Ad')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['ad'],
            },
        ),
    ]
